function modelPath = build_fmcw_fpga_algorithm_simulink()
%BUILD_FMCW_FPGA_ALGORITHM_SIMULINK 创建FIL可替换的FPGA算法联合仿真模型。

modelName = 'FMCW_FPGA_Algorithm_Sim';
repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(repoRoot);
startup_fmcwlidar_sil();
modelDirectory = fullfile(repoRoot, 'models');
modelPath = fullfile(modelDirectory, [modelName '.slx']);
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
    rehash;
end

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'simTs', 'StartTime', '0', ...
    'StopTime', 'simFpgaStopTime', 'SaveTime', 'on', ...
    'TimeSaveName', 'tout', 'SignalLogging', 'off');

add_block('simulink/Sources/Constant', [modelName '/Enable'], ...
    'Value', 'true', 'OutDataTypeStr', 'boolean', ...
    'Position', [25 125 80 155]);
add_block('simulink/Sources/From Workspace', [modelName '/Reset'], ...
    'VariableName', 'simFpgaReset', 'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'Position', [20 180 90 215]);
add_block('simulink/Sources/Constant', [modelName '/External fault'], ...
    'Value', 'false', 'OutDataTypeStr', 'boolean', ...
    'Position', [20 240 90 270]);
add_block('simulink/Signal Routing/From', [modelName '/ADC code feedback'], ...
    'GotoTag', 'ADC_CODE', 'Position', [20 70 90 100]);
add_block('simulink/Signal Routing/Goto', [modelName '/Reset distribution'], ...
    'GotoTag', 'RESET_SIGNAL', 'Position', [105 185 175 210]);

controllerBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/FPGA Algorithm DUT'], 'Position', [205 55 415 335]);
set_param(controllerBlock, 'System', 'FMCWFPGAController', ...
    'OpenFcn', 'open_fmcwlidar_manual(''FPGA'');');
dacBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/16 bit DAC'], 'Position', [650 70 760 120]);
set_param(dacBlock, 'System', 'FPGAOffsetBinaryDAC', ...
    'OpenFcn', 'open_fmcwlidar_manual(''DAC'');');
ldcBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/LDC220C'], 'Position', [850 60 975 130]);
set_param(ldcBlock, 'System', 'LDC220CModel', ...
    'OpenFcn', 'open_fmcwlidar_manual(''LDC220C'');');
laserBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/BNLD1550 laser'], 'Position', [1065 45 1210 260]);
set_param(laserBlock, 'System', 'BNLD1550Laser', ...
    'OpenFcn', 'open_fmcwlidar_manual(''BNLD1550'');');
mziBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/50 ns MZI'], 'Position', [1290 70 1405 150]);
set_param(mziBlock, 'System', 'MZIInterferometerModel', ...
    'OpenFcn', 'open_fmcwlidar_manual(''MZI'');');
pdbBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/PDB450C'], 'Position', [1480 70 1595 150]);
set_param(pdbBlock, 'System', 'PDB450CModel', ...
    'OpenFcn', 'open_fmcwlidar_manual(''PDB450C'');');
adcBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/14 bit ADC'], 'Position', [1670 70 1785 135]);
set_param(adcBlock, 'System', 'FPGASignedADC', ...
    'OpenFcn', 'open_fmcwlidar_manual(''ADC'');');
add_block('simulink/Discrete/Unit Delay', [modelName '/ADC register'], ...
    'InitialCondition', 'int16(0)', 'SampleTime', 'simTs', ...
    'Position', [1835 75 1890 125]);
add_block('simulink/Signal Routing/Goto', [modelName '/ADC feedback return'], ...
    'GotoTag', 'ADC_CODE', 'Position', [1930 85 2010 115]);

add_block('simulink/Sources/Constant', [modelName '/Temperature setpoint'], ...
    'Value', 'simTemperatureSetpointC', 'Position', [850 350 975 380]);
tedBlock = add_block('simulink/User-Defined Functions/MATLAB System', ...
    [modelName '/TED200C'], 'Position', [1065 330 1200 395]);
set_param(tedBlock, 'System', 'TED200CModel', ...
    'OpenFcn', 'open_fmcwlidar_manual(''TED200C'');');
add_block('simulink/Sources/Constant', [modelName '/Sample time'], ...
    'Value', 'simTs', 'Position', [925 420 1015 450]);
add_block('simulink/Sources/Constant', [modelName '/Phase noise'], ...
    'Value', '0', 'Position', [925 465 1015 495]);
add_block('simulink/Signal Routing/From', [modelName '/Laser reset'], ...
    'GotoTag', 'RESET_SIGNAL', 'Position', [925 510 1015 540]);

add_line(modelName, 'ADC code feedback/1', 'FPGA Algorithm DUT/1', 'autorouting', 'on');
add_line(modelName, 'Enable/1', 'FPGA Algorithm DUT/2', 'autorouting', 'on');
add_line(modelName, 'Reset/1', 'FPGA Algorithm DUT/3', 'autorouting', 'on');
add_line(modelName, 'Reset/1', 'Reset distribution/1', 'autorouting', 'on');
add_line(modelName, 'External fault/1', 'FPGA Algorithm DUT/4', 'autorouting', 'on');
add_line(modelName, 'FPGA Algorithm DUT/1', '16 bit DAC/1', 'autorouting', 'on');
add_line(modelName, '16 bit DAC/1', 'LDC220C/1', 'autorouting', 'on');
add_line(modelName, 'LDC220C/1', 'BNLD1550 laser/1', 'autorouting', 'on');
add_line(modelName, 'Temperature setpoint/1', 'TED200C/1', 'autorouting', 'on');
add_line(modelName, 'TED200C/1', 'BNLD1550 laser/2', 'autorouting', 'on');
add_line(modelName, 'Sample time/1', 'BNLD1550 laser/3', 'autorouting', 'on');
add_line(modelName, 'Phase noise/1', 'BNLD1550 laser/4', 'autorouting', 'on');
add_line(modelName, 'Laser reset/1', 'BNLD1550 laser/5', 'autorouting', 'on');
add_line(modelName, 'BNLD1550 laser/1', '50 ns MZI/1', 'autorouting', 'on');
add_line(modelName, '50 ns MZI/1', 'PDB450C/1', 'autorouting', 'on');
add_line(modelName, '50 ns MZI/2', 'PDB450C/2', 'autorouting', 'on');
add_line(modelName, 'PDB450C/1', '14 bit ADC/1', 'autorouting', 'on');
add_line(modelName, '14 bit ADC/1', 'ADC register/1', 'autorouting', 'on');
add_line(modelName, 'ADC register/1', 'ADC feedback return/1', 'autorouting', 'on');

unusedSources = {'BNLD1550 laser/1','BNLD1550 laser/2', ...
    'BNLD1550 laser/4','BNLD1550 laser/5','BNLD1550 laser/6'};
unusedNames = {'Main optical terminator','Optical power terminator', ...
    'Wavelength terminator','Monitor current terminator','Phase terminator'};
for k = 1:numel(unusedNames)
    y = 585 + 35 * (k - 1);
    add_block('simulink/Sinks/Terminator', [modelName '/' unusedNames{k}], ...
        'Position', [1225 y 1245 y + 20]);
    add_line(modelName, unusedSources{k}, [unusedNames{k} '/1'], ...
        'autorouting', 'on');
end

add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [modelName '/Driver safe'], 'Operator', 'NOT', ...
    'Position', [995 145 1035 175]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [modelName '/Detector safe'], 'Operator', 'NOT', ...
    'Position', [1610 145 1650 175]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [modelName '/ADC safe'], 'Operator', 'NOT', ...
    'Position', [1800 145 1840 175]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [modelName '/Controller safe'], 'Operator', 'NOT', ...
    'Position', [455 305 495 335]);
add_line(modelName, 'LDC220C/2', 'Driver safe/1', 'autorouting', 'on');
add_line(modelName, 'PDB450C/2', 'Detector safe/1', 'autorouting', 'on');
add_line(modelName, '14 bit ADC/2', 'ADC safe/1', 'autorouting', 'on');
add_line(modelName, 'FPGA Algorithm DUT/8', 'Controller safe/1', 'autorouting', 'on');

safeNames = {'DRIVER_SAFE','TEMPERATURE_SAFE','LASER_SAFE', ...
    'DETECTOR_SAFE','ADC_SAFE','CONTROLLER_SAFE'};
safeSources = {'Driver safe/1','TED200C/2','BNLD1550 laser/7', ...
    'Detector safe/1','ADC safe/1','Controller safe/1'};
gotoPositions = [1045 145 1125 170; 1215 365 1295 390; ...
    1225 235 1305 260; 1660 145 1740 170; ...
    1850 145 1930 170; 505 305 585 330];
for k = 1:numel(safeNames)
    add_block('simulink/Signal Routing/Goto', ...
        [modelName '/Safe tag ' num2str(k)], ...
        'GotoTag', safeNames{k}, 'Position', gotoPositions(k,:));
    add_line(modelName, safeSources{k}, ['Safe tag ' num2str(k) '/1'], ...
        'autorouting', 'on');
end
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [modelName '/All limits OK'], 'Operator', 'AND', 'Inputs', '6', ...
    'Position', [1870 470 1925 570]);
for k = 1:numel(safeNames)
    y = 465 + 22 * k;
    add_block('simulink/Signal Routing/From', ...
        [modelName '/Safe input ' num2str(k)], ...
        'GotoTag', safeNames{k}, 'Position', [1740 y 1825 y + 20]);
    add_line(modelName, ['Safe input ' num2str(k) '/1'], ...
        ['All limits OK/' num2str(k)], 'autorouting', 'on');
end

probeNames = {'fpgaDacCode','fpgaChirpStart','fpgaChirpActive', ...
    'fpgaLutWriteEnable','fpgaPhaseErrorHz','fpgaControllerState', ...
    'fpgaChirpNumber','fpgaFault','fpgaDacVoltageV','driveCurrentA', ...
    'laserFrequencyHz','mziRfVoltageV','fpgaAdcCode','withinLimits'};
probeSources = {'FPGA Algorithm DUT/1','FPGA Algorithm DUT/2', ...
    'FPGA Algorithm DUT/3','FPGA Algorithm DUT/4', ...
    'FPGA Algorithm DUT/5','FPGA Algorithm DUT/6', ...
    'FPGA Algorithm DUT/7','FPGA Algorithm DUT/8', ...
    '16 bit DAC/1','LDC220C/1','BNLD1550 laser/3', ...
    'PDB450C/1','14 bit ADC/1','All limits OK/1'};
probePositions = [440 45 590 70; 440 80 590 105; 440 115 590 140; ...
    440 150 590 175; 440 185 590 210; 440 220 590 245; ...
    440 255 590 280; 440 345 590 370; 650 150 800 175; ...
    850 190 1000 215; 1065 270 1215 295; 1480 190 1630 215; ...
    1670 190 1820 215; 1950 505 2100 530];
for k = 1:numel(probeNames)
    add_block('simulink/Sinks/To Workspace', ...
        [modelName '/' probeNames{k}], ...
        'VariableName', probeNames{k}, 'SaveFormat', 'Timeseries', ...
        'MaxDataPoints', 'inf', 'Position', probePositions(k,:));
    add_line(modelName, probeSources{k}, [probeNames{k} '/1'], ...
        'autorouting', 'on');
end

annotationText = sprintf([ ...
    'FIL边界：FPGA Algorithm DUT（4输入/8输出）\n' ...
    '3 GHz/50 us扫频；50 ns MZI拍频3 MHz；FPGA时钟100 MHz。\n' ...
    '状态：1 PRECHARGE, 2 CHIRP, 3 UPDATE, 4 IDLE, 5 FAULT\n' ...
    'ADC/DAC均为整数接口；To Workspace仅为测试探针。']);
annotation = Simulink.Annotation(modelName, annotationText);
annotation.Position = [20 600 610 670];
set_param(modelName, 'ZoomFactor', 'FitSystem');
save_system(modelName, modelPath);
close_system(modelName, 0);
end
