function libraryPath = build_fmcwlidar_sil_library()
%BUILD_FMCWLIDAR_SIL_LIBRARY 生成可拖放的独立器件Simulink库。

repoRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(repoRoot);
startup_fmcwlidar_sil();
load_system('simulink');

libraryName = 'FMCWLidar_SIL_Library';
libraryPath = fullfile(repoRoot, 'models', [libraryName '.slx']);
if bdIsLoaded(libraryName)
    close_system(libraryName, 0);
end
if isfile(libraryPath)
    delete(libraryPath);
    rehash;
end


new_system(libraryName, 'Library');
set_param(libraryName, 'Lock', 'off');
set_param(libraryName, 'ZoomFactor', 'FitSystem');

addSystemBlock(libraryName, 'FPGA controller', 'FMCWFPGAController', ...
    [35 150 260 420], 'lightBlue', '3 GHz | 100 MHz', 'FPGA');
addSystemBlock(libraryName, '16 bit DAC', 'FPGAOffsetBinaryDAC', ...
    [330 225 570 335], 'cyan', 'uint16 -> V', 'DAC');
addSystemBlock(libraryName, 'LDC220C current driver', 'LDC220CModel', ...
    [640 210 920 350], 'green', '50 kHz | 206 mA/V', 'LDC220C');
addSystemBlock(libraryName, 'BNLD1550 DFB laser', 'BNLD1550Laser', ...
    [1000 140 1280 425], 'yellow', '1550 nm | 100 kHz', 'BNLD1550');
addSystemBlock(libraryName, '50 ns MZI', 'MZIInterferometerModel', ...
    [1370 210 1600 350], 'orange', 'delay = 50 ns', 'MZI');
addSystemBlock(libraryName, 'PDB450C balanced detector', 'PDB450CModel', ...
    [1680 200 1980 360], 'magenta', '4 MHz | 50 kV/A', 'PDB450C');
addSystemBlock(libraryName, '14 bit ADC', 'FPGASignedADC', ...
    [2070 215 2300 345], 'cyan', 'V -> int16', 'ADC');
addSystemBlock(libraryName, 'TED200C temperature controller', 'TED200CModel', ...
    [1000 510 1280 640], 'green', '15..35 degC', 'TED200C');

add_block('simulink/Ports & Subsystems/Subsystem', ...
    [libraryName '/Documentation'], ...
    'Position', [35 510 260 625], ...
    'BackgroundColor', 'lightBlue', ...
    'ForegroundColor', 'black', ...
    'FontWeight', 'bold');
Simulink.SubSystem.deleteContents([libraryName '/Documentation']);
addDocumentation([libraryName '/Documentation']);

header = Simulink.Annotation(libraryName, sprintf([ ...
    'FMCW LiDAR SOFTWARE-IN-THE-LOOP DEVICE LIBRARY\n' ...
    'Double-click a hardware device to open its PDF manual; use Block Parameters to edit model settings.']));
header.Position = [35 25 2300 90];
header.FontSize = 16;
header.FontWeight = 'bold';
header.ForegroundColor = 'blue';

flow = Simulink.Annotation(libraryName, sprintf([ ...
    'Recommended signal direction: FPGA controller -> DAC -> LDC220C -> BNLD1550 -> MZI -> PDB450C -> ADC -> FPGA controller\n' ...
    'TED200C drives the laser temperature input. All continuous quantities use SI units.']));
flow.Position = [330 500 920 640];
flow.FontSize = 11;

notice = Simulink.Annotation(libraryName, sprintf([ ...
    'MODEL STATUS: behavioral SIL with integer ADC/DAC boundaries. atan2 is a CORDIC reference; this library is not synthesizable RTL.\n' ...
    'Double-click LDC220C, TED200C, BNLD1550, or PDB450C for its PDF; open Documentation for all interfaces.']));
notice.Position = [35 705 2300 790];
notice.FontSize = 11;
notice.BackgroundColor = 'lightBlue';

set_param(libraryName, 'Lock', 'on');
save_system(libraryName, libraryPath);
close_system(libraryName, 0);
end

function addSystemBlock(libraryName, blockName, className, position, ...
        color, label, documentKey)
blockPath = [libraryName '/' blockName];
block = add_block('simulink/User-Defined Functions/MATLAB System', ...
    blockPath, 'Position', position);
if any(strcmpi(documentKey, {'LDC220C','TED200C','BNLD1550','PDB450C'}))
    label = sprintf('%s\nDouble-click: PDF manual', label);
else
    label = sprintf('%s\nDouble-click: model docs', label);
end
set_param(block, ...
    'System', className, ...
    'BackgroundColor', color, ...
    'ForegroundColor', 'black', ...
    'FontWeight', 'bold', ...
    'AttributesFormatString', label, ...
    'OpenFcn', sprintf('open_fmcwlidar_manual(''%s'');', documentKey));
end

function addDocumentation(documentationPath)
titleText = Simulink.Annotation(documentationPath, sprintf([ ...
    'FMCW LiDAR SIL - Embedded Documentation\n' ...
    'The port order below matches each MATLAB System block.']));
titleText.Position = [30 20 1220 80];
titleText.FontSize = 16;
titleText.FontWeight = 'bold';
titleText.ForegroundColor = 'blue';

interfaces = Simulink.Annotation(documentationPath, sprintf([ ...
    '16 bit DAC: dacCode(uint16) -> voltageV(V)\n' ...
    'LDC220C: modulationVoltageV(V) -> driveCurrentA(A), limited\n' ...
    'TED200C: setpointC(degC) -> laserTemperatureC(degC), withinRange\n' ...
    'BNLD1550: driveCurrentA, temperatureC, sampleTimeS, phaseNoiseUnit, resetPhase\n' ...
    '            -> opticalField(sqrt(W)), opticalPowerW, frequencyHz, wavelengthM, monitorCurrentA, phaseRad, withinRange\n' ...
    '50 ns MZI: opticalField -> powerPlusW, powerMinusW\n' ...
    'PDB450C: powerPlusW, powerMinusW -> rfVoltageV, saturated\n' ...
    '14 bit ADC: voltageV -> adcCode(int16), clipped\n' ...
    'FPGA: adcCode, enable, reset, faultIn -> dacCode, chirpStart, chirpActive, lutWriteEnable, phaseErrorHz, state, chirpNumber, faultOut']));
interfaces.Position = [30 115 1340 390];
interfaces.FontSize = 11;
interfaces.BackgroundColor = 'white';

baseline = Simulink.Annotation(documentationPath, sprintf([ ...
    'VERIFIED 3 GHz BASELINE\n' ...
    '50 us chirp | 50 ns MZI | 3 MHz beat | 100 MHz sample rate | theoretical range resolution 4.997 cm\n' ...
    'Sixth chirp: RMS 160.97 kHz | peak 746.56 kHz | sweep 3.002217 GHz | no clipping/fault\n\n' ...
    'LIMITATIONS\n' ...
    'Deterministic behavioral simulation only. No RTL timing, CDC/FIFO, Vivado implementation, FIL, or hardware validation.\n' ...
    'PDF lookup: docs/manuals -> parent FMCW project manuals -> vendor product page.\n' ...
    'Repository documents: README.md, docs/DEVICE_INTERFACES.md, docs/SIL_STATUS.md']));
baseline.Position = [30 435 1340 650];
baseline.FontSize = 11;
baseline.BackgroundColor = 'lightBlue';
end
